export const actions = {
  FILTER_BY_SIZE: "FILTER_BY_SIZE",
  FILTER_BY_BRAND: "FILTER_BY_BRAND",
  FILTER_BY_STOCK: "FILTER_BY_STOCK",
  FILTER_BY_GENDER: "FILTER_BY_GENDER",
  SORT_BY_PRICE: "SORT_BY_PRICE",
  RESET_FILTERS: "RESET_FILTERS",
};
